# Original work (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2018.
# Modified work (c) William Belle, 2018-2020.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "12"
script: npm run build
