# (c) William Belle, 2021-2022.
# See the LICENSE file for more details.

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install and test
        run: |
          npm i
          npm run build
